//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRAP.WCF.Client.IRAPWCFClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IRAPJsonTable", Namespace="http://schemas.datacontract.org/2004/07/IRAP.Interface.Global")]
    [System.SerializableAttribute()]
    public partial class IRAPJsonTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonContent {
            get {
                return this.JsonContentField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonContentField, value) != true)) {
                    this.JsonContentField = value;
                    this.RaisePropertyChanged("JsonContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRAPWCFClient.IServiceIRAPGlobal")]
    public interface IServiceIRAPGlobal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIRAPGlobal/ExChange", ReplyAction="http://tempuri.org/IServiceIRAPGlobal/ExChangeResponse")]
        int ExChange(string assemblyName, string className, string methodName, System.Collections.Generic.List<IRAP.WCF.Client.IRAPWCFClient.IRAPJsonTable> jsonTable, ref string jsonContent, out string backTypeFullName, out string errText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIRAPGlobal/GetBinary", ReplyAction="http://tempuri.org/IServiceIRAPGlobal/GetBinaryResponse")]
        byte[] GetBinary(out int errCode, out string errText, string assemblyName, string className, string methodName, System.Collections.Hashtable paramDict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIRAPGlobal/UploadBinary", ReplyAction="http://tempuri.org/IServiceIRAPGlobal/UploadBinaryResponse")]
        string UploadBinary(out int errCode, out string errText, string assemblyName, string className, string methodName, byte[] binaryBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIRAPGlobal/WCFRESTful", ReplyAction="http://tempuri.org/IServiceIRAPGlobal/WCFRESTfulResponse")]
        int WCFRESTful(string assemblyName, string className, string methodName, System.Collections.Generic.List<IRAP.WCF.Client.IRAPWCFClient.IRAPJsonTable> jsonTable, ref string jsonContent, out string backTypeFullName, out string errText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceIRAPGlobalChannel : IRAP.WCF.Client.IRAPWCFClient.IServiceIRAPGlobal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceIRAPGlobalClient : System.ServiceModel.ClientBase<IRAP.WCF.Client.IRAPWCFClient.IServiceIRAPGlobal>, IRAP.WCF.Client.IRAPWCFClient.IServiceIRAPGlobal {
        
        public ServiceIRAPGlobalClient() {
        }
        
        public ServiceIRAPGlobalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceIRAPGlobalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIRAPGlobalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIRAPGlobalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ExChange(string assemblyName, string className, string methodName, System.Collections.Generic.List<IRAP.WCF.Client.IRAPWCFClient.IRAPJsonTable> jsonTable, ref string jsonContent, out string backTypeFullName, out string errText) {
            return base.Channel.ExChange(assemblyName, className, methodName, jsonTable, ref jsonContent, out backTypeFullName, out errText);
        }
        
        public byte[] GetBinary(out int errCode, out string errText, string assemblyName, string className, string methodName, System.Collections.Hashtable paramDict) {
            return base.Channel.GetBinary(out errCode, out errText, assemblyName, className, methodName, paramDict);
        }
        
        public string UploadBinary(out int errCode, out string errText, string assemblyName, string className, string methodName, byte[] binaryBytes) {
            return base.Channel.UploadBinary(out errCode, out errText, assemblyName, className, methodName, binaryBytes);
        }
        
        public int WCFRESTful(string assemblyName, string className, string methodName, System.Collections.Generic.List<IRAP.WCF.Client.IRAPWCFClient.IRAPJsonTable> jsonTable, ref string jsonContent, out string backTypeFullName, out string errText) {
            return base.Channel.WCFRESTful(assemblyName, className, methodName, jsonTable, ref jsonContent, out backTypeFullName, out errText);
        }
    }
}
